### ISSUE TITLE
Scan cancelled / Plugin times out

### ISSUE THREAD

**Issue by FroodyHoop** [abhishekabhi789/GCS_for_Tasker#1]

**Comment by FroodyHoop** [comment]
Does not work when launched as an action called from a task unless you save/update the configuration before each use. Without saving the configuration from the task that calls it before every use, one of two errors are seen (it seems random as to which one):

15.00.49/ActionArgBundle Scan Action Configuration: extra key not found in bundle:
15.00.49/E FIRE PLUGIN: Scan Action Configuration / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 5 bundle keys
15.00.49/E Scan Action Configuration: plugin comp: com.abhi.gcsfortasker/com.joaomgcd.taskerpluginlibrary.action.IntentServiceAction
15.00.49/Ew add wait type Plugin1 time 60
15.00.49/Ew add wait type Plugin1 done
15.00.49/E handlePluginFinish: taskExeID: 1 result 3
15.00.49/E pending result code
15.00.49/E add wait task
15.00.49/E Error: 2
15.00.49/E Scan cancelled

-- or --

15.03.50/ActionArgBundle Scan Action Configuration: extra key not found in bundle:
15.03.50/E FIRE PLUGIN: Scan Action Configuration / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 5 bundle keys
15.03.50/E Scan Action Configuration: plugin comp: com.abhi.gcsfortasker/com.joaomgcd.taskerpluginlibrary.action.IntentServiceAction
15.03.50/Ew add wait type Plugin2 time 60
15.03.50/Ew add wait type Plugin2 done
15.03.50/E handlePluginFinish: taskExeID: 2 result 3
15.03.50/E pending result code
15.03.50/E add wait task
15.04.50/E Error: 2
15.04.50/E Plugin did not respond before timing out. You can change the timeout value in the action's configuration.

**Comment by abhishekabhi789** [comment]
Thanks for test report. I couldn't reproduce this issue exactly, but found both errors by lowering the timeout. I'll look into this.

**Comment by abhishekabhi789** [comment]
Hi, I made an attempt to fix the issue. Please try the [latest release](https://github.com/abhishekabhi789/GCS_for_Tasker/releases/tag/v0.5.3).
If the problem persists, please reopen this issue.
